<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE0fh3ym\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE0fh3ym/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE0fh3ym.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE0fh3ym\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE0fh3ym\appProdProjectContainer([
    'container.build_hash' => 'E0fh3ym',
    'container.build_id' => 'a6330e86',
    'container.build_time' => 1632317838,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE0fh3ym');
