<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCc6isyg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCc6isyg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCc6isyg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCc6isyg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCc6isyg\appProdProjectContainer([
    'container.build_hash' => 'Cc6isyg',
    'container.build_id' => 'b5e16eba',
    'container.build_time' => 1631711665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCc6isyg');
